<?php

namespace AppBundle\Repository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends \Doctrine\ORM\EntityRepository {

	public function countEmployee() {

		$query = $this->createQueryBuilder('q')
				->select('COUNT(q)');

		return $query->getQuery()->getSingleScalarResult();
	}
	
	public function topEmployee() {
		// SELECT employee.prenom, employee.nom, job.job, 
		// SUM(employee.cout_jour*time.day) AS cout FROM time, employee, job 
		// WHERE time.employee_id = employee.id AND employee.job_id = job.id 
		// GROUP BY employee.prenom, employee.nom, job.job 
		// ORDER BY cout DESC 
		// LIMIT 0,1
		
				$query = $this->createQueryBuilder('e')
				->select('e.prenom, e.nom, e.picture, e.dateEmbauche, j.job, SUM(e.coutJour*t.day) AS cout')
				->from('AppBundle:Job', 'j')
				->from('AppBundle:Time', 't')
				->where('j.id=e.job')
				->andWhere('e.id=t.employee')
				->groupBy('e.prenom, e.nom, e.picture, e.dateEmbauche, j.job')
				->orderBy('cout', 'DESC')
				->setMaxResults(1)
				->setFirstResult(10);

		return $query->getQuery()->getResult();
		
	}

}
