<?php

namespace AppBundle\Repository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{
		
	public function groupByjob() {
	
		$query = $this->createQueryBuilder('q')
				->select('q')
				->groupBy('q.id');
		
		return $query->getQuery()->getResult();
	}
	
	public function countJob() {

		$query = $this->createQueryBuilder('q')
				->select('COUNT(q)');

		return $query->getQuery()->getSingleScalarResult();
	}
	
}
