<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository {

	public function countProject() {

		$query = $this->createQueryBuilder('q')
				->select('COUNT(q)');

		return $query->getQuery()->getSingleScalarResult();
	}

	public function countProjectFinished() {

		$query = $this->createQueryBuilder('q')
				->select('COUNT(q)')
				->where('q.livre=1');

		return $query->getQuery()->getSingleScalarResult();
	}

}
