<?php

namespace AppBundle\Repository;

/**
 * TimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeRepository extends \Doctrine\ORM\EntityRepository {

	public function countProductionDays() {

		// SELECT count(*) FROM time WHERE 1

		$query = $this->createQueryBuilder('t')
				->select('COUNT(t)');

		return $query->getQuery()->getSingleScalarResult();
	}

	public function productionTime() {
		// SELECT employee.nom, employee.prenom, time.day, project.intitule 
		// FROM employee, project, time 
		// WHERE employee.id = time.employee_id 
		// AND project.id = time.project_id 
		// ORDER BY project.date_creation 
		// DESC LIMIT 0, 8

		$query = $this->createQueryBuilder('t')
				->select('e.id, e.nom, e.prenom, t.day, p.id AS proid, p.intitule')
				->from('AppBundle:Employee', 'e')
				->from('AppBundle:Project', 'p')
				->where('e.id=t.employee')
				->andWhere('p.id=t.project')
				->groupBy('e.id, e.nom, e.prenom, t.day, p.id, p.intitule, p.dateCreation')
				->orderBy('p.dateCreation', 'DESC')
				->setMaxResults(8)
				->setFirstResult(10);

		return $query->getQuery()->getResult();
	}

}
